// Code generated by raindrop build, DO NOT EDIT.
import { Ai, Annotation, App, KvCache, Logger, MRNObject, ServiceStub, SmartBucket, SmartMemory, SqlDatabase, Tracer,  } from '@liquidmetal-ai/raindrop-framework';

export interface Env {
  _raindrop: {
    app: App;
  };
  AI: Ai;
  annotation: Annotation<Omit<MRNObject, 'type' | 'applicationName' | 'versionId'>>;
  API_GATEWAY: ServiceStub<import('../api-gateway/index.js').default>;
  CALMLY_DB: SqlDatabase;
  COACHING_ENGINE: ServiceStub<import('../coaching-engine/index.js').default>;
  logger: Logger;
  mem: KvCache;
  SCENARIO_LIBRARY: SmartBucket;
  tracer: Tracer;
  USER_MEMORY: SmartMemory;
}
